Lecture03
1127akinori/RaiseTech pull request #3
Opened 2023-12-28 04:24 UTC by 1127akinori

確認お願いします

2023-12-28 04:28 UTC, 1127akinori commented
第３回の課題です。
ご確認お願いします。

2023-12-28 10:12 UTC, MasatoshiMizumoto requested changes
> `<img width="1512" alt="スクリーンショット 2023-12-21 0 01 59" src="https://github.com/1127akinori/RaiseTech/assets/149952775/1fb5afc2-256d-441c-9a39-a5ab53e71e8f">`

この画像の登録方法だと、自分で保存場所も名前もコントロールできないので、お手数ですが文書と同じようにpushで格納いただいて表示してほしいです！
Cloud9ではプレビューが正しく動きませんのでGitHub上で表示を確認しながらご対応ください！

2024-01-08 15:47 UTC, MasatoshiMizumoto requested changes
Markdown記法についてコメント入れてますのでご対応お願いします！！

2024-01-08 15:47 UTC, MasatoshiMizumoto commented on lecture03.md
> +Railsを動かすためのアプリケーションサーバーの一種
段落は改行が反映されないので、この場合はリストが良いと思います！
```suggestion
- Puma vesion5.6.5
- Railsを動かすためのアプリケーションサーバーの一種
```

2024-01-08 15:47 UTC, MasatoshiMizumoto commented on lecture03.md
> +$ sudo service mysqld status
- 全角と半角は間違えないように提出前にチェックしてくださいね！
- 今回の部分だとこんな感じが良いかなと思います。
- 見出し1（一番大きい物）は基本的にページに1つだけがWebページのルールなので、見出しを多用するなら見出し2から使ってください！

```suggestion
# DBサーバーについて調べる

## Mysqlログイン(-pはパスあり)
mysql -u root -p
## Mysqlの起動
sudo service mysqld start
## Mysqlの停止
$ sudo service mysqld stop
## MySQLの再起動
$ sudo service mysqld restart
## Mysqlの状態確認
$ sudo service mysqld status
```

2024-01-08 15:58 UTC, MasatoshiMizumoto approved these changes
LGTM!

2024-01-08 16:13 UTC, merged